package com.toolbox.modbus.tcplistener;

public enum ModbusCommandType {
    WRITE_STRING_TO_REGISTERS,
    WRITE_DINT_TO_REGISTERS,
    WRITE_HIGH_BYTE_TO_REGISTERS,
    WRITE_LOW_BYTE_TO_REGISTERS,
    READ_STRING_FROM_REGISTERS,
    READ_DINT_FROM_REGISTERS,
    READ_HIGH_BYTE_FROM_REGISTERS,
    READ_LOW_BYTE_FROM_REGISTERS,
    CLEAR_MEMORY_FROM_REGISTERS;

}